# Generated by Django 4.1.5 on 2023-03-09 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("control_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entity_User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("firs_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                (
                    "tenant_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="control_app.tenant",
                    ),
                ),
            ],
        ),
    ]
