# Generated by Django 4.1.7 on 2023-04-20 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquenationalform',
            name='petition_responsible',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='control_app.petitionresponsible'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professionalresponsible',
            name='profession_name_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Profession Name+', to='control_app.professionname'),
        ),
    ]
