# Generated by Django 4.1.5 on 2023-04-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("control_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="licenceholderresponsible",
            name="sign",
        ),
        migrations.RemoveField(
            model_name="petitionresponsible",
            name="sign",
        ),
        migrations.RemoveField(
            model_name="professionalresponsible",
            name="sign",
        ),
        migrations.AlterField(
            model_name="cadastral",
            name="estrato",
            field=models.IntegerField(),
        ),
    ]
