# Generated by Django 4.1.5 on 2023-04-12 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("control_app", "0002_remove_licenceholderresponsible_sign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenceholderresponsible",
            name="sign",
            field=models.BooleanField(default=True, verbose_name="Sign"),
        ),
        migrations.AddField(
            model_name="petitionresponsible",
            name="sign",
            field=models.BooleanField(default=True, verbose_name="Sign"),
        ),
        migrations.AddField(
            model_name="professionalresponsible",
            name="sign",
            field=models.BooleanField(default=True, verbose_name="Sign"),
        ),
    ]
