# Generated by Django 4.1.5 on 2023-04-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("control_app", "0003_licenceholderresponsible_sign_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenceholderresponsible",
            name="electronic_notification",
            field=models.BooleanField(
                default=True, verbose_name="¿Acepta Notificación Electrónica?"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="licenceholderresponsible",
            name="sign",
            field=models.BooleanField(verbose_name="Firma"),
        ),
        migrations.AlterField(
            model_name="petitionresponsible",
            name="sign",
            field=models.BooleanField(verbose_name="Firma"),
        ),
        migrations.AlterField(
            model_name="professionalresponsible",
            name="sign",
            field=models.BooleanField(verbose_name="Firma"),
        ),
    ]
