# Generated by Django 4.1.5 on 2023-03-10 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("control_app", "0003_action_document_procedure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolepermissions",
            name="description",
            field=models.CharField(
                default="Modificar estado de tramite", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="action",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="document",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="entity_user",
            name="tenant_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="control_app.tenant"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="timestamp",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="control_app.entity_user",
            ),
        ),
    ]
