# Generated by Django 4.1.5 on 2023-03-23 00:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("control_app", "0004_rolepermissions_description_alter_action_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timestamp",
            old_name="action_id",
            new_name="action",
        ),
        migrations.RenameField(
            model_name="timestamp",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AddField(
            model_name="timestamp",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="entity_user",
            name="first_name",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="entity_user",
            name="last_name",
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name="timestamp",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
