# Generated by Django 4.1.5 on 2023-04-12 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("control_app", "0005_alter_bordersdimensionareas_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionalresponsible",
            name="required_review",
            field=models.BooleanField(
                default=False, verbose_name="¿Exige Supervisión Tecnica?"
            ),
            preserve_default=False,
        ),
    ]
