# Generated by Django 4.1.5 on 2023-04-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("control_app", "0006_professionalresponsible_required_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="professionalresponsible",
            name="licence_expedition",
            field=models.DateField(default="2023-01-01"),
            preserve_default=False,
        ),
    ]
