# Generated by Django 4.1.7 on 2023-04-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0007_professionalresponsible_licence_expedition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalresponsible',
            name='professional_licence_num',
            field=models.IntegerField(verbose_name='Prof Lic Num'),
        ),
    ]
