# Generated by Django 4.1.7 on 2023-04-18 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0008_alter_professionalresponsible_professional_licence_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='brsustainabledeclarationmeasure',
            name='measure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='control_app.measure'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brsustainabledeclarationmeasure',
            name='sustainable_declaration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='control_app.sustainabledeclaration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sustainabledeclaration',
            name='measures',
            field=models.ManyToManyField(blank=True, through='control_app.BrSustainableDeclarationMeasure', to='control_app.measure'),
        ),
        migrations.AlterUniqueTogether(
            name='brsustainabledeclarationmeasure',
            unique_together={('sustainable_declaration', 'measure')},
        ),
        migrations.RemoveField(
            model_name='brsustainabledeclarationmeasure',
            name='measure_id',
        ),
        migrations.RemoveField(
            model_name='brsustainabledeclarationmeasure',
            name='sustainable_declaration_id',
        ),
    ]
