# Generated by Django 4.1.7 on 2023-04-18 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_app', '0009_brsustainabledeclarationmeasure_measure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brsustainabledeclarationmeasure',
            old_name='measure',
            new_name='measure_id',
        ),
        migrations.RenameField(
            model_name='brsustainabledeclarationmeasure',
            old_name='sustainable_declaration',
            new_name='sustainable_declaration_id',
        ),
        migrations.AlterUniqueTogether(
            name='brsustainabledeclarationmeasure',
            unique_together={('sustainable_declaration_id', 'measure_id')},
        ),
    ]
