version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings_dev
    volumes:
      - project-volume:/app:cached
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - app-network
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migrator
  
  migrator:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings_dev
    volumes:
      - project-volume:/app
    command: /app/migrate_load_fixtures.sh
    networks:
      - app-network
    depends_on:
      - db


  db:
    image: postgres:13
    env_file: .env
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network


volumes:
  project-volume:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/../../
      o: bind
  postgres-data:

networks:
  app-network:
    driver: bridge