version: '3.8'

services:
  app:
    build:
      dockerfile: Dockerfile

    volumes:
      - ../../:/app:cached

    networks:
      - app-network


  db:
    image: postgres:13
    env_file: .dev.development
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network


volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge